import { describe, expect, it } from "vitest";

import {
  continuationIdentityForSelection,
  nativeModelSelection,
} from "../../src/shared/model-routing";
import { parseServerEvent } from "../../src/shared/contracts/server-event-schema";

const selection = nativeModelSelection({
  providerId: "codex",
  modelId: "gpt-test",
  reasoningEffort: "high",
});

const changedFile = {
  path: "src/example.ts",
  status: "modified",
  insertions: 2,
  deletions: 1,
  untracked: false,
  staged: false,
  unstaged: true,
  indexStatus: " ",
  worktreeStatus: "M",
};

const diff = {
  patch: "diff --git a/src/example.ts b/src/example.ts\n",
  truncated: false,
  files: [changedFile],
};

const conversation = {
  id: "conversation-1",
  projectId: "project-1",
  title: "Boundary",
  providerId: "codex",
  modelSelection: selection,
  continuationIdentity: null,
  model: "gpt-test",
  reasoningEffort: "high",
  interactionMode: "build",
  accessMode: "supervised",
  status: "idle",
  attentionKind: null,
  branch: "main",
  worktreePath: null,
  providerSessionId: null,
  archivedAt: null,
  settledAt: null,
  completedAt: null,
  lastViewedAt: null,
  createdAt: "2030-01-01T00:00:00.000Z",
  updatedAt: "2030-01-01T00:00:00.000Z",
};

const conversationDetail = {
  conversation,
  agentTurns: [{
    id: "turn-1",
    conversationId: conversation.id,
    runId: "run-1",
    userMessageId: "message-1",
    terminalAssistantMessageId: null,
    providerId: "codex",
    modelSelection: selection,
    continuationIdentity: continuationIdentityForSelection(selection),
    harnessId: selection.harnessId,
    backendProfileId: selection.backendProfileId,
    model: selection.modelId,
    modelAlias: null,
    reasoningEffort: "high",
    interactionMode: "build",
    accessMode: "supervised",
    providerSessionBefore: null,
    providerSessionAfter: null,
    requestedAt: conversation.createdAt,
    startedAt: conversation.createdAt,
    completedAt: null,
    status: "running",
    terminalReason: null,
    checkpointId: null,
    usageAtStart: null,
    usageAtCompletion: null,
    configurationRevision: 1,
    association: "authoritative",
    createdAt: conversation.createdAt,
    updatedAt: conversation.updatedAt,
  }],
  turnGitArtifacts: [{
    id: "artifact-1",
    turnId: "turn-1",
    conversationId: conversation.id,
    runId: "run-1",
    repositoryIdentity: null,
    worktreeIdentity: null,
    branch: "main",
    beforeCheckpointId: null,
    beforeFingerprint: null,
    afterFingerprint: null,
    files: [{ ...changedFile, previousPath: null, binary: false }],
    insertions: 2,
    deletions: 1,
    status: "ready",
    completeness: "complete",
    patchState: "available",
    patchDigest: "sha256:patch",
    capturedAt: conversation.createdAt,
    terminalAssistantMessageId: null,
    failureReason: null,
    absenceReason: null,
  }],
  messages: [{
    id: "message-1",
    conversationId: conversation.id,
    turnId: null,
    role: "user",
    content: "Inspect this.",
    attachments: [],
    createdAt: conversation.createdAt,
  }],
  activities: [{
    id: "activity-1",
    conversationId: conversation.id,
    runId: "run-1",
    turnId: "turn-1",
    kind: "tool",
    title: "Inspect",
    detail: null,
    status: "completed",
    createdAt: conversation.createdAt,
  }],
  subagents: [{
    id: "trace-1",
    conversationId: conversation.id,
    runId: "run-1",
    turnId: "turn-1",
    providerId: "codex",
    providerTaskId: null,
    providerAgentId: null,
    parentTraceId: null,
    parentProviderAgentId: null,
    parentProviderToolUseId: null,
    providerToolUseId: null,
    providerRole: null,
    providerName: null,
    providerStatus: null,
    status: "completed",
    isLive: false,
    description: null,
    progress: null,
    result: null,
    sequence: 1,
    createdAt: conversation.createdAt,
    updatedAt: conversation.updatedAt,
  }],
  reasonings: [{
    id: "reasoning-1",
    conversationId: conversation.id,
    runId: "run-1",
    turnId: "turn-1",
    content: "Checked.",
    status: "completed",
    createdAt: conversation.createdAt,
  }],
  usage: [{
    conversationId: conversation.id,
    turnId: "turn-1",
    usedTokens: 10,
    totalProcessedTokens: 10,
    totalProcessedScope: "run",
    maxTokens: 100,
    inputTokens: 8,
    cachedInputTokens: 0,
    cacheWriteInputTokens: 0,
    outputTokens: 2,
    reasoningOutputTokens: 0,
    compactsAutomatically: false,
    updatedAt: conversation.updatedAt,
  }],
  plans: [{
    conversationId: conversation.id,
    runId: "run-1",
    turnId: "turn-1",
    explanation: null,
    steps: [{ step: "Inspect", status: "completed" }],
  }],
  goals: [{
    conversationId: conversation.id,
    source: "inertia-local",
    providerSessionId: null,
    objective: "Inspect safely",
    status: "active",
    tokenBudget: null,
    tokensUsed: null,
    timeUsedSeconds: null,
    createdAt: conversation.createdAt,
    updatedAt: conversation.updatedAt,
    synchronizedAt: null,
  }],
  checkpoints: [{
    id: "checkpoint-1",
    conversationId: conversation.id,
    turnId: "turn-1",
    ref: "refs/inertia/checkpoint",
    label: "Before",
    turnIndex: 1,
    filesChanged: 1,
    insertions: 2,
    deletions: 1,
    createdAt: conversation.createdAt,
  }],
  reviewSummaries: [{
    conversationId: conversation.id,
    fingerprint: "diff",
    providerId: "codex",
    harnessId: selection.harnessId,
    backendProfileId: selection.backendProfileId,
    model: selection.modelId,
    overall: "Looks good.",
    classifications: [],
    files: [],
    generatedAt: conversation.updatedAt,
  }],
  reviewStates: [{
    conversationId: conversation.id,
    repositoryPath: ".",
    scope: "file",
    path: "src/example.ts",
    hunkId: null,
    targetFingerprint: "file",
    reviewed: true,
    stale: false,
    updatedAt: conversation.updatedAt,
  }],
  reviewNotes: [{
    id: "note-1",
    conversationId: conversation.id,
    repositoryPath: ".",
    path: "src/example.ts",
    hunkId: null,
    lineIds: [],
    targetFingerprint: "file",
    body: "Reviewed.",
    stale: false,
    createdAt: conversation.createdAt,
    updatedAt: conversation.updatedAt,
  }],
};

function event(result: Record<string, unknown>): unknown {
  return {
    type: "request.result",
    requestId: "request-1",
    result,
  };
}

const pullRequest = {
  available: true,
  remoteName: "origin",
  forge: "github",
  unavailableReason: null,
};

describe("server event request-result trust boundary", () => {
  it.each([
    {
      kind: "workspace.entries",
      directory: "src",
      entries: [{ path: "src/example.ts", kind: "file" }],
      truncated: false,
    },
    {
      kind: "workspace.file",
      file: {
        path: "src/example.ts",
        content: "export {};",
        truncated: false,
        language: "typescript",
        contentDigest: "sha256:abc",
        modifiedAt: "2030-01-01T00:00:00.000Z",
        authorityRef: "authority-1",
      },
    },
    {
      kind: "git.branches",
      branches: [{ name: "main", current: true, remote: false, worktreePath: null }],
    },
    {
      kind: "project.actions",
      actions: [{ id: "test", label: "Test", command: "npm test", preview: false }],
    },
    { kind: "duo.pending", launchIds: ["launch-1"], hasMore: false },
    {
      kind: "duo.prepared",
      launchId: "launch-1",
      state: "prepared",
      sides: [
        { ordinal: 0, conversationId: "conversation-1", turnId: "turn-1" },
        { ordinal: 1, conversationId: "conversation-2", turnId: "turn-2" },
      ],
      comparison: { conversationId: "conversation-3" },
    },
    {
      kind: "duo.status",
      launchId: "launch-1",
      state: "running",
      error: null,
      sides: [
        { ordinal: 0, conversationId: "conversation-1", turnId: "turn-1", dispatchState: "started" },
        { ordinal: 1, conversationId: "conversation-2", turnId: "turn-2", dispatchState: "started" },
      ],
      comparison: {
        state: "waiting",
        conversationId: null,
        turnId: null,
        attempt: 0,
        error: null,
      },
    },
    {
      kind: "git.status",
      status: {
        isRepository: true,
        authorityRef: "authority-1",
        root: "/repo",
        branch: "main",
        upstream: "origin/main",
        ahead: 0,
        behind: 0,
        hasRemote: true,
        pullRequest,
        files: [changedFile],
        insertions: 2,
        deletions: 1,
      },
    },
    {
      kind: "git.workspace.status",
      status: {
        repositories: [{
          repositoryPath: ".",
          authorityRef: "authority-1",
          state: "ready",
          error: null,
          branch: "main",
          upstream: "origin/main",
          ahead: 0,
          behind: 0,
          hasRemote: true,
          pullRequest,
          files: [changedFile],
          insertions: 2,
          deletions: 1,
          clean: false,
          truncated: false,
        }],
        files: 1,
        insertions: 2,
        deletions: 1,
        scannedDirectories: 2,
        skippedDirectories: 0,
        discoveredRepositories: 1,
        repositoryLimit: 64,
        partial: false,
        truncated: false,
        issues: [],
      },
    },
    { kind: "git.diff", diff },
    {
      kind: "git.workspace.diff",
      diff: { ...diff, repositoryPath: ".", reviewMetadataChanged: false },
    },
    {
      kind: "git.turn.diff",
      diff: {
        ...diff,
        artifactId: "artifact-1",
        turnId: "turn-1",
        title: "Turn changes",
        completeness: "complete",
        patchState: "available",
      },
    },
    {
      kind: "git.reversal.plan",
      plan: {
        authorityRef: "authority-1",
        filePath: "src/example.ts",
        hunkId: "hunk-1",
        hunkHeader: "@@ -1 +1 @@",
        selectedLineCount: 1,
        changedLineCount: 1,
        affectedLayers: ["worktree"],
        validation: {
          diffFingerprint: "diff",
          fileFingerprint: "file",
          hunkFingerprint: "hunk",
          selectionFingerprint: "selection",
          gitStateFingerprint: "state",
        },
      },
    },
    {
      kind: "git.reversal",
      diff,
      operation: {
        id: "operation-1",
        authorityRef: "authority-1",
        repositoryPath: ".",
        filePath: "src/example.ts",
        selectedLineCount: 1,
        affectedLayers: ["worktree"],
        createdAt: "2030-01-01T00:00:00.000Z",
      },
    },
    {
      kind: "review.selection.answer",
      answer: {
        conversationId: conversation.id,
        repositoryPath: ".",
        fingerprint: "diff",
        filePath: "src/example.ts",
        hunkId: "hunk-1",
        selectedLineCount: 1,
        question: "Safe?",
        answer: "Yes.",
        providerId: "codex",
        modelSelection: selection,
        generatedAt: "2030-01-01T00:00:00.000Z",
      },
    },
    {
      kind: "review.summary",
      summary: {
        conversationId: conversation.id,
        fingerprint: "diff",
        providerId: "codex",
        harnessId: selection.harnessId,
        backendProfileId: selection.backendProfileId,
        model: selection.modelId,
        overall: "Looks good.",
        classifications: [{ classification: "test-impact", evidence: "Tests changed." }],
        files: [{
          path: "src/example.ts",
          summary: "Safe change.",
          classifications: [],
          hunks: [{ hunkId: "hunk-1", summary: "Guarded.", classifications: [] }],
        }],
        generatedAt: "2030-01-01T00:00:00.000Z",
      },
    },
    {
      kind: "conversation.detail",
      conversationId: conversation.id,
      state: "ready",
      detail: conversationDetail,
      sync: { runtimeGeneration: "runtime-1", latestSequence: 4 },
    },
  ])("accepts a complete $kind projection", (result) => {
    expect(parseServerEvent(event(result))).toMatchObject({
      type: "request.result",
      result: { kind: result.kind },
    });
  });

  it.each([
    { kind: "workspace.entries", directory: "", entries: [{ path: "x" }], truncated: false },
    { kind: "workspace.file", file: { path: "x", content: 7 } },
    { kind: "git.branches", branches: [{ name: "main", current: "yes" }] },
    { kind: "project.actions", actions: [{ id: "test", label: "Test", command: "x", preview: "no" }] },
    { kind: "duo.pending", launchIds: [7], hasMore: false },
    {
      kind: "duo.prepared",
      launchId: "launch",
      state: "prepared",
      sides: [
        { ordinal: 0, conversationId: "one", turnId: "turn" },
        { ordinal: 0, conversationId: "two", turnId: "turn" },
      ],
    },
    {
      kind: "git.status",
      status: { files: [{ ...changedFile, insertions: "2" }] },
    },
    { kind: "git.workspace.status", status: { repositories: [{ repositoryPath: "." }] } },
    { kind: "git.diff", diff: { patch: "", truncated: false, files: [{ path: "x" }] } },
    { kind: "git.reversal.plan", plan: { filePath: "x", validation: {} } },
    { kind: "git.reversal", diff, operation: { id: "operation" } },
    {
      kind: "review.selection.answer",
      answer: { conversationId: "conversation", modelSelection: { ...selection, capabilities: [{}] } },
    },
    {
      kind: "review.summary",
      summary: {
        conversationId: "conversation",
        fingerprint: "diff",
        providerId: "codex",
        harnessId: null,
        backendProfileId: null,
        model: null,
        overall: "Broken",
        classifications: [{ classification: "invented", evidence: "No." }],
        files: [],
        generatedAt: "now",
      },
    },
    {
      kind: "conversation.detail",
      conversationId: conversation.id,
      state: "ready",
      detail: {
        ...conversationDetail,
        messages: [{ ...conversationDetail.messages[0], attachments: [{ id: "bad" }] }],
      },
    },
  ])("rejects malformed nested $kind state", (result) => {
    expect(() => parseServerEvent(event(result))).toThrow("Malformed server event");
  });
});
