export const MAC_TRAFFIC_LIGHT_POSITION = { x: 16, y: 17 } as const;
export const WINDOW_HEADER_HEIGHT = 48;
export const MAC_TRAFFIC_LIGHT_CLUSTER_WIDTH = 54;
export const MAC_BRAND_MIN_CLEAR_GAP = 24;
export const MAC_BRAND_SAFE_INSET = MAC_TRAFFIC_LIGHT_POSITION.x
  + MAC_TRAFFIC_LIGHT_CLUSTER_WIDTH
  + MAC_BRAND_MIN_CLEAR_GAP;
