import { type JsonObject, type RpcId } from "./protocol";

/**
 * Snapshot of the generated Codex App Server 0.149 ServerRequest
 * discriminants. The scheduled provider drift probe compares this exhaustive
 * disposition table with bindings generated by the latest official CLI.
 */
export const CODEX_APP_SERVER_REQUEST_DISPOSITIONS = {
  "item/commandExecution/requestApproval": "handled",
  "item/fileChange/requestApproval": "handled",
  "item/tool/requestUserInput": "handled",
  "mcpServer/elicitation/request": "declined",
  "item/permissions/requestApproval": "handled",
  "item/tool/call": "handled",
  "account/chatgptAuthTokens/refresh": "unsupported",
  "attestation/generate": "disabled",
  "currentTime/read": "handled",
  applyPatchApproval: "handled",
  execCommandApproval: "handled",
} as const;

export type CodexAppServerRequestMethod =
  keyof typeof CODEX_APP_SERVER_REQUEST_DISPOSITIONS;

interface CodexCurrentTimeRead {
  threadId: string;
}

interface CodexMcpElicitationOwnership {
  threadId: string;
  turnId: string | null;
}

const CURRENT_TIME_READ_METHOD = "currentTime/read";
const MCP_ELICITATION_METHOD = "mcpServer/elicitation/request";

export function isCodexCurrentTimeReadMethod(method: string): boolean {
  return method === CURRENT_TIME_READ_METHOD;
}

export function parseCodexCurrentTimeRead(
  method: string,
  params: JsonObject,
): CodexCurrentTimeRead | undefined {
  if (!isCodexCurrentTimeReadMethod(method)) return undefined;
  const threadId = parseCodexProviderThreadId(params);
  return threadId ? { threadId } : undefined;
}

export function parseCodexProviderThreadId(
  params: JsonObject,
): string | undefined {
  return strictIdentifier(params.threadId);
}

export function codexCurrentTimeReadResult(nowMs = Date.now()): {
  currentTimeAt: number;
} {
  return { currentTimeAt: Math.floor(nowMs / 1_000) };
}

export function isCodexMcpElicitationMethod(method: string): boolean {
  return method === MCP_ELICITATION_METHOD;
}

/**
 * Parses only the ownership fields needed to decline an elicitation safely.
 * Inertia deliberately does not reinterpret MCP typed or URL forms as its
 * narrower question contract.
 */
export function parseCodexMcpElicitationOwnership(
  method: string,
  params: JsonObject,
): CodexMcpElicitationOwnership | undefined {
  if (!isCodexMcpElicitationMethod(method)) return undefined;
  const threadId = strictIdentifier(params.threadId);
  const turnId =
    params.turnId === null ? null : strictIdentifier(params.turnId);
  const serverName = strictIdentifier(params.serverName);
  const mode = params.mode;
  if (
    !threadId ||
    turnId === undefined ||
    !serverName ||
    (mode !== "form" && mode !== "openai/form" && mode !== "url")
  )
    return undefined;
  return { threadId, turnId };
}

interface CodexAuxiliaryServerRequestHost {
  id: RpcId;
  method: string;
  params: JsonObject;
  isOwnedProviderThread: (threadId: string) => boolean;
  isOwnedProviderTurn: (threadId: string, turnId: string) => boolean;
  writeMessage: (message: JsonObject) => boolean;
  setLastError: (message: string) => void;
  emitActivity: (phase: "info" | "failed", label: string) => void;
  cancel: () => void;
}

/** Handles bounded App Server requests that do not open a UI interaction. */
export function handleCodexAuxiliaryServerRequest(
  host: CodexAuxiliaryServerRequestHost,
): boolean {
  const currentTimeRead = parseCodexCurrentTimeRead(host.method, host.params);
  if (currentTimeRead) {
    if (!host.isOwnedProviderThread(currentTimeRead.threadId)) {
      return rejectOwnedRequest(
        host,
        "Codex requested the current time for a different provider thread.",
      );
    }
    host.writeMessage({ id: host.id, result: codexCurrentTimeReadResult() });
    return true;
  }
  if (isCodexCurrentTimeReadMethod(host.method)) {
    return rejectOwnedRequest(host, "Codex sent a malformed current-time request.");
  }

  const elicitation = parseCodexMcpElicitationOwnership(
    host.method,
    host.params,
  );
  if (elicitation) {
    const owned = elicitation.turnId === null
      ? host.isOwnedProviderThread(elicitation.threadId)
      : host.isOwnedProviderTurn(elicitation.threadId, elicitation.turnId);
    if (!owned) {
      return rejectOwnedRequest(
        host,
        "Codex sent an MCP elicitation for a different provider turn.",
      );
    }
    host.writeMessage({
      id: host.id,
      result: { action: "decline", content: null, _meta: null },
    });
    host.emitActivity(
      "info",
      "MCP elicitation declined because this client cannot safely represent it",
    );
    return true;
  }
  if (isCodexMcpElicitationMethod(host.method)) {
    return rejectOwnedRequest(
      host,
      "Codex sent a malformed MCP elicitation request.",
    );
  }
  return false;
}

function rejectOwnedRequest(
  host: CodexAuxiliaryServerRequestHost,
  message: string,
): true {
  host.writeMessage({ id: host.id, error: { code: -32602, message } });
  host.setLastError(message);
  host.emitActivity("failed", message);
  host.cancel();
  return true;
}

function strictIdentifier(value: unknown): string | undefined {
  if (typeof value !== "string" || value.includes("\0")) return undefined;
  const identifier = value.trim();
  return identifier && identifier === value && identifier.length <= 1_000
    ? identifier
    : undefined;
}
